name: Doctest build

on: 
  push:
    paths-ignore:
      - 'locale/**'

  pull_request:
    paths-ignore:
      - 'locale/**'

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  doctest:

    runs-on: ubuntu-latest
    name: Doctest

    services:
      image: docker

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      with:
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
      with:
        python-version: 3.9
    - name: Pip upgrade
      run: |
          python -m pip install --upgrade pip
    - name: Build test code
      run: |
          make -f docker.mk doctest
    - name: Upload build artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: Doctest build
        path: ./build/doctest/output.txt
